# Generated by Django 5.1.5 on 2025-03-06 18:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario_mascota', '0002_mascota_es_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amistades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('mascota_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario_mascota.mascota')),
            ],
        ),
    ]
