# Generated by Django 5.1.5 on 2025-03-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('especie', models.CharField(max_length=50)),
                ('edad', models.PositiveIntegerField()),
                ('raza', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=250)),
                ('foto_perfil', models.URLField()),
                ('preferencias', models.TextField()),
                ('contraseña', models.CharField(max_length=250)),
            ],
        ),
    ]
