# Generated by Django 5.1.5 on 2025-03-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_mascota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='es_admin',
            field=models.BooleanField(default=False),
        ),
    ]
