# Generated by Django 5.1.5 on 2025-03-14 07:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_mascota', '0002_mascota_es_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='contraseña',
        ),
        migrations.AddField(
            model_name='mascota',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mascota',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='password',
            field=models.CharField(default='defaultpassword123', max_length=128),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre_usuario',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
