# Generated by Django 5.1.5 on 2025-03-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_mascota', '0003_remove_mascota_contraseña_mascota_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
