# Generated by Django 5.1.5 on 2025-04-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_mascota', '0004_alter_mascota_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='foto_perfil',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='preferencias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
