# Generated by Django 5.1.5 on 2025-04-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_mascota', '0005_alter_mascota_edad_alter_mascota_especie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
