# Generated by Django 5.1.5 on 2025-03-06 18:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imagenes', '0001_initial'),
        ('usuario_mascota', '0002_mascota_es_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('contenido', models.TextField()),
                ('img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imagenes.imagenes')),
                ('mascota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario_mascota.mascota')),
            ],
        ),
    ]
