# Generated by Django 5.1.5 on 2025-03-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_posts_img_imagenes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenes',
            name='imagen',
        ),
        migrations.AddField(
            model_name='imagenes',
            name='imagen_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
