# Generated by Django 5.1.5 on 2025-04-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_imagenes_imagen_imagenes_imagen_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
